# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reactome_analysis_api.models.base_model_ import Model
from reactome_analysis_api import util


class ExternalDataDefaultParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, value: str=None):  # noqa: E501
        """ExternalDataDefaultParameters - a model defined in Swagger

        :param name: The name of this ExternalDataDefaultParameters.  # noqa: E501
        :type name: str
        :param value: The value of this ExternalDataDefaultParameters.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'name': str,
            'value': str
        }

        self.attribute_map = {
            'name': 'name',
            'value': 'value'
        }

        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'ExternalDataDefaultParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExternalData_default_parameters of this ExternalDataDefaultParameters.  # noqa: E501
        :rtype: ExternalDataDefaultParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ExternalDataDefaultParameters.

        Name of the parameter. This is either the parameter name as returned by the /methods function or one of the following strings to specify a field in the request object: comparison_group_1,  comparison_group_2.  # noqa: E501

        :return: The name of this ExternalDataDefaultParameters.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ExternalDataDefaultParameters.

        Name of the parameter. This is either the parameter name as returned by the /methods function or one of the following strings to specify a field in the request object: comparison_group_1,  comparison_group_2.  # noqa: E501

        :param name: The name of this ExternalDataDefaultParameters.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self) -> str:
        """Gets the value of this ExternalDataDefaultParameters.


        :return: The value of this ExternalDataDefaultParameters.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this ExternalDataDefaultParameters.


        :param value: The value of this ExternalDataDefaultParameters.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
